apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
  namespace: kasten-io
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    name: http
  selector:
    service: gateway
  loadBalancerIP: 10.140.10.70
