apiVersion: v1
kind: Service
metadata:
  name: sock-shop-lb
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8079
    name: http
  selector:
    name: front-end
  loadBalancerIP: 10.140.10.71
